name: Snake

on:
  schedule:
    - cron: "0 0 * * *" # Ejecuta una vez al día
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Run GitHub Snake
        run: |
          npm install
          npm run generate
      - name: Commit "Snake" update
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Snake"
          branch: main
